[SMAN-102] Create desktop gui for OnlineServicesEmulator
sanducristina-alexandra/OnlineServicesEmulator pull request #4
Opened 2023-06-19 11:20 UTC by radu1351

CR URL: https://jira.harman.com/jira/browse/SMAN-102
CHANGES: Created the GUI
Testing: No testing required

2023-06-19 11:58 UTC, sebi1995 requested changes

2023-06-19 11:58 UTC, sebi1995 commented on pom.xml
>      </dependency>
format the code,
for however cute java 20 might feel and look, please restrict yourself to java 9
also only create the bare bones of the application, just something that will start up, a blank, the other features of the application are addressed in the other tickets

2023-06-20 09:22 UTC, sebi1995 requested changes

2023-06-20 09:22 UTC, sebi1995 commented on src/main/java/com/example/onlineservicesemulator/Application.java
> +public class Application extends javafx.application.Application {
rename application to OnlineServicesEmulator
and remove javafx.application.

2023-06-20 09:22 UTC, sebi1995 commented on pom.xml
>          <plugins>
these plugins were for a different task

2023-06-20 09:22 UTC, sebi1995 commented on src/main/java/com/example/onlineservicesemulator/Controller.java
> +package com.example.onlineservicesemulator;
this class will be for a different task, delete it

2023-06-20 13:16 UTC, AndreiK83 approved these changes

2023-06-20 13:16 UTC, AndreiK83 commented
There are no major changes, so you can merge it to the main branch ;)

2023-06-21 07:00 UTC, merged